### ISSUE TITLE
Request to change the URL

### ISSUE THREAD

**Issue by Brainfold** [0x4D31/awesome-threat-detection#5]
I am the author of the content "Threat Hunting Techniques - AV, Proxy, DNS and HTTP Logs" mentioned in the list under "Resources Section" of "awesome-threat-detection . Thanks for including. 

I  have moved my blog from "brainfold.net" to "www.cyberhuntz.com". Can you please update the list as the old link redirects to fake flash update and I don't control the domain anymore. 

https://www.cyberhuntz.com/2016/08/threat-hunting-techniques-av-proxy-dns.html

Thanks.

**Comment by 0x4D31** [comment]
@Brainfold Oh, ok. Thanks for letting me know. :)
Updated
